"""RMESHV — Reticulum Mesh application entry point."""

import json
import sys
import time
from pathlib import Path
from PyQt6.QtWidgets import QApplication, QMessageBox

from src.backend.rns_node import ReticulumNode
from src.backend.lxmf_messenger import LXMFMessenger
from src.backend.contact_manager import ContactManager
from src.backend.network_monitor import NetworkMonitor
from src.ui.main_window import MainWindow


class Application:
    def __init__(self):
        self.rns_config_dir = Path.home() / ".reticulum"
        self.app_config_dir = Path.home() / ".config" / "rmeshv"
        self.app_config_dir.mkdir(parents=True, exist_ok=True)

        self.downloads_dir = Path.home() / "Downloads" / "RMESHV"
        self.downloads_dir.mkdir(parents=True, exist_ok=True)

        self.rns_node = None
        self.lxmf_messenger = None
        self.contact_manager = None
        self.network_monitor = None
        self.main_window = None

        self._config_path = self.app_config_dir / "config.json"
        self._config = self._load_config()

        self._init_backend()

    def _load_config(self) -> dict:
        if self._config_path.exists():
            try:
                return json.loads(self._config_path.read_text())
            except:
                pass
        return {"display_name": "", "message_filter": "all"}

    def _save_config(self):
        self._config_path.write_text(json.dumps(self._config, indent=2))

    def get_display_name(self) -> str:
        name = self._config.get("display_name", "")
        if name:
            return name
        if self.rns_node:
            return self.rns_node.get_short_identity_hash()
        return "RMESHV User"

    def set_display_name(self, name: str):
        self._config["display_name"] = name
        self._save_config()
        if self.lxmf_messenger:
            self.lxmf_messenger.set_display_name(name)

    def get_message_filter(self) -> str:
        return self._config.get("message_filter", "all")

    def set_message_filter(self, mode: str):
        self._config["message_filter"] = mode
        self._save_config()

    def is_sender_allowed(self, sender_hash: str) -> bool:
        mode = self.get_message_filter()
        if mode == "all":
            return True
        if mode == "trusted":
            if self.contact_manager:
                return self.contact_manager.check_trusted(sender_hash)
            return False
        if mode == "blocked":
            return False
        return True

    def _ensure_rns_config(self):
        config_path = self.rns_config_dir / "config"
        if not config_path.exists():
            self._create_default_rns_config(config_path)
            return

        try:
            text = config_path.read_text()
            additions = []

            if "AutoInterface" not in text:
                additions.append("\n[[AutoInterface]]\n  type = AutoInterface\n  interface_enabled = Yes\n")

            if "TCPServerInterface" not in text:
                additions.append("\n[[TCP Server]]\n  type = TCPServerInterface\n  interface_enabled = Yes\n  listen_ip = 0.0.0.0\n  listen_port = 4242\n")

            if additions:
                config_path.write_text(text.rstrip() + "\n" + "\n".join(additions))
                print("[RMESHV] Added AutoInterface + TCPServerInterface to config")
        except Exception as e:
            print(f"[RMESHV] Config note: {e}")

    def _create_default_rns_config(self, config_path):
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text("""# Reticulum configuration
# Generated by RMESHV

[reticulum]
  enable_transport = No
  share_instance = Yes
  shared_instance_port = 37428

[[AutoInterface]]
  type = AutoInterface
  interface_enabled = Yes

[[TCP Server]]
  type = TCPServerInterface
  interface_enabled = Yes
  listen_ip = 0.0.0.0
  listen_port = 4242
""")

    def _init_backend(self):
        try:
            self._ensure_rns_config()
            self.rns_node = ReticulumNode(
                rns_config_dir=str(self.rns_config_dir),
                app_config_dir=str(self.app_config_dir)
            )
            if not self.rns_node or not self.rns_node.reticulum:
                print("Reticulum node failed to initialize")
                return

            self.contact_manager = ContactManager(str(self.app_config_dir))

            identity = self.rns_node.get_identity()
            if identity:
                self.lxmf_messenger = LXMFMessenger(
                    identity,
                    storage_dir=str(self.app_config_dir / "lxmf"),
                    display_name=self.get_display_name()
                )
                self.lxmf_messenger.set_message_callback(self._on_lxmf_message)

                self.network_monitor = NetworkMonitor(
                    self.rns_node.reticulum,
                    identity
                )
                self.network_monitor.start()

        except Exception as e:
            print(f"Backend initialization error: {e}")
            import traceback
            traceback.print_exc()

    def announce_now(self):
        display_name = self.get_display_name()
        if self.lxmf_messenger:
            return self.lxmf_messenger.announce(display_name)
        return False

    def _on_lxmf_message(self, sender_hash: str, content: str, title: str, timestamp: float):
        if self.contact_manager:
            self.contact_manager.touch(sender_hash)
        if self.main_window and hasattr(self.main_window, "messages_widget"):
            try:
                self.main_window.messages_widget.receive_lxmf_message(sender_hash, content, title, timestamp)
            except Exception as e:
                print(f"[LXMF] UI delivery error: {e}")

    def send_message(self, dest_hash: str, text: str):
        if self.lxmf_messenger:
            return self.lxmf_messenger.send_message(dest_hash, text)
        return False

    def run(self):
        app = QApplication(sys.argv)

        if self.rns_node is None or getattr(self.rns_node, 'reticulum', None) is None:
            QMessageBox.warning(
                None,
                "Reticulum Issue",
                "Reticulum had trouble starting. Some features may be limited."
            )

        self.main_window = MainWindow(self)

        if self.lxmf_messenger:
            self.lxmf_messenger.set_message_callback(self._on_lxmf_message)

        sys.exit(app.exec())


def main():
    application = Application()
    application.run()


if __name__ == "__main__":
    main()
